/* ==========================================================================
   221B LABS — CAREERS DATA
   Edit this file to add, remove, or update departments and roles.
   Every role currently opens Part-time only (see app.js form logic).
   ========================================================================== */

const DEPARTMENTS = [
  {
    id: "sales",
    code: "S",
    name: "Sales",
    tagline: "Bring in the clients. Own the revenue. Build the pipeline that builds us.",
    description:
      "Sales at 221B Labs isn't a support function — it's the engine. We're an early-stage startup building AI products, SaaS, and custom software for businesses that need to move fast, and every deal you close funds the next thing we build. This team is highly performance-driven: the people who hustle, follow up relentlessly, and actually close get noticed, get rewarded, and get promoted. If you want a quota to hide behind, this isn't it. If you want ownership over your pipeline and your income, keep reading.",
    roles: [
      {
        id: "sales-executive",
        title: "Sales Executive",
        oneLiner: "Cold call, close, repeat — and get paid for what you actually bring in.",
        summary:
          "You'll be on the front line of 221B Labs' growth — calling prospects, running client meetings, and closing deals for our AI, SaaS, and custom software offerings. This is a Performance-Based Opportunity: your base activity gets you in the room, but your closes are what get rewarded. We're a startup, so you'll have real ownership over your pipeline from day one, not a script you're chained to.",
        responsibilities: [
          "Make cold calls and outbound outreach to potential clients daily",
          "Run client meetings and product/service walkthroughs",
          "Close deals and own the full conversation from first contact to signature",
          "Follow up consistently on warm leads so nothing dies in the pipeline",
          "Drive measurable revenue generation month over month",
        ],
        requirements: [
          "Confident communicator who isn't afraid of cold outreach or rejection",
          "Comfortable owning a number and being measured against it",
          "Fast learner — you'll need to speak intelligently about AI and software products quickly",
          "Self-starter who doesn't need constant supervision to stay productive",
          "Open to freshers and experienced candidates alike — attitude matters more than tenure",
        ],
        niceToHave: [
          "Prior experience in tech, SaaS, or B2B sales",
          "Existing network in the Hyderabad startup or SME ecosystem",
          "Familiarity with CRM tools",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "business-development-executive",
        title: "Business Development Executive",
        oneLiner: "Open new doors, build partnerships, and turn conversations into revenue.",
        summary:
          "You'll hunt for new business opportunities that don't yet exist in our pipeline — strategic partnerships, LinkedIn outreach, and networking that turns into real proposals. This is a Performance-Based Opportunity built for someone who sees an untapped market and moves on it before being asked. Outstanding performers here get first look at leadership tracks as we scale.",
        responsibilities: [
          "Identify and pursue new business opportunities across target markets",
          "Build strategic partnerships that create long-term value for 221B Labs",
          "Run consistent LinkedIn outreach and personal networking campaigns",
          "Lead proposal discussions and shape early-stage deal terms",
          "Report on pipeline health and business development impact",
        ],
        requirements: [
          "Strong initiative — you should be comfortable creating opportunities, not just following them",
          "Confident written and verbal communication for outreach and proposals",
          "Genuine curiosity about how businesses and industries operate",
          "Comfortable navigating ambiguity in an early-stage environment",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience with LinkedIn Sales Navigator or similar outreach tools",
          "Prior exposure to partnerships or alliance-building roles",
          "Background in B2B software or services sales",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "client-success-executive",
        title: "Client Success Executive",
        oneLiner: "Keep clients winning, so they keep choosing us.",
        summary:
          "Once a deal closes, you take over — onboarding new clients, managing the relationship, and making sure they see real value from day one. This is a Performance-Based Opportunity centered on retention and growth: the better you manage relationships, the more upsell and renewal opportunities you unlock, and the faster you grow with us.",
        responsibilities: [
          "Own client onboarding and set the tone for the entire relationship",
          "Manage day-to-day client relationships and act as their trusted point of contact",
          "Provide proactive client support before small issues become big ones",
          "Identify and execute on upselling opportunities within existing accounts",
          "Drive retention through consistent, high-quality client experience",
        ],
        requirements: [
          "Naturally empathetic communicator who makes people feel heard",
          "Organised enough to manage multiple client relationships simultaneously",
          "Comfortable having commercial conversations, not just support conversations",
          "Fast learner who can speak credibly about our AI and software products",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Prior experience in account management or customer success",
          "Exposure to subscription or retainer-based client models",
          "Basic understanding of software delivery timelines",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "sales-operations-associate",
        title: "Sales Operations Associate",
        oneLiner: "Make the pipeline visible so the team can move faster.",
        summary:
          "You'll be the backbone that keeps our sales engine organised — CRM hygiene, reporting, and lead tracking that lets the whole team make sharper decisions. This is a Performance-Based Opportunity for someone who finds satisfaction in clean data and clear numbers, and who wants to understand the mechanics of a growing sales org from the inside.",
        responsibilities: [
          "Maintain accurate, up-to-date records across our CRM and pipeline tools",
          "Build and maintain sales reports that leadership actually uses",
          "Track leads through every stage of the pipeline and flag stalls",
          "Own sales documentation, playbooks, and process consistency",
          "Analyse sales data to surface trends and improvement opportunities",
        ],
        requirements: [
          "Comfortable with spreadsheets, CRMs, and structured data",
          "Detail-oriented — small errors in reporting compound fast",
          "Analytical mindset with a habit of asking 'what does this number actually mean'",
          "Organised self-starter who doesn't need micromanagement",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience with CRM platforms (HubSpot, Zoho, or similar)",
          "Comfortable with basic data analysis or dashboarding tools",
          "Exposure to sales or revenue operations",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
    ],
  },

  {
    id: "marketing",
    code: "M",
    name: "Marketing",
    tagline: "Build the brand. Drive the demand. Prove it with data.",
    description:
      "Marketing at 221B Labs owns everything that makes people notice us before we ever pick up the phone — brand building, lead generation, growth experiments, content, and social presence. We move fast, test constantly, and let the analytics decide what wins. If you're someone who treats every campaign as an experiment rather than a checklist, and you want your work seen by real clients (not buried in a deck), this team is built for you.",
    roles: [
      {
        id: "digital-marketing-executive",
        title: "Digital Marketing Executive",
        oneLiner: "Turn ad spend into pipeline, not just impressions.",
        summary:
          "You'll plan, launch, and optimise paid campaigns across Google and Meta that bring real leads to our sales team. This is a Performance-Based Opportunity — the campaigns that convert are the ones that get more budget and more credit, and the marketer who can prove ROI moves up fast.",
        responsibilities: [
          "Plan and run paid campaigns on Google Ads and Meta Ads Manager",
          "Continuously optimise campaigns for cost-per-lead and conversion quality",
          "Analyse performance data and reallocate budget toward what's working",
          "Collaborate with content and design on ad creative and landing pages",
          "Report on lead generation metrics with real accountability for results",
        ],
        requirements: [
          "Working knowledge of Google Ads and/or Meta Ads Manager",
          "Comfortable reading analytics dashboards and drawing real conclusions",
          "Understanding of marketing funnels from impression to closed lead",
          "Experimental mindset — you test, measure, and iterate rather than guess",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Google Ads or Meta Blueprint certification",
          "Experience marketing B2B or software products",
          "Basic understanding of SEO and how it complements paid",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "social-media-manager",
        title: "Social Media Manager",
        oneLiner: "Own the platforms where people decide if we're legit.",
        summary:
          "You'll run 221B Labs' presence across Instagram and LinkedIn — building a content calendar, engaging our community, and growing a brand that looks like it belongs to a company doing serious work. This is a Performance-Based Opportunity for someone who wants real ownership over how a growing startup shows up online.",
        responsibilities: [
          "Plan and execute a consistent content calendar across Instagram and LinkedIn",
          "Write and coordinate day-to-day social content that reflects our voice",
          "Engage actively with our community — comments, DMs, and mentions",
          "Track engagement metrics and adjust strategy based on real performance",
          "Drive measurable brand growth across every platform we're on",
        ],
        requirements: [
          "Demonstrated experience running social accounts for a brand or business",
          "Understanding of how content performs differently across platforms",
          "Comfortable with content tools like Canva or similar",
          "Genuine sense of brand voice and consistency",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Basic video editing or Reels experience",
          "Experience growing a B2B LinkedIn presence specifically",
          "Familiarity with social scheduling tools",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "content-marketing-specialist",
        title: "Content Marketing Specialist",
        oneLiner: "Write the words that make people trust us before we've even talked.",
        summary:
          "You'll write blog posts, website copy, case studies, and email content that explains complex AI and software work in a way real people want to read. This is a Performance-Based Opportunity for a writer who cares as much about clarity and conversion as about good sentences.",
        responsibilities: [
          "Write blog posts and website copy in a clear, non-generic voice",
          "Build email marketing content that nurtures leads toward conversion",
          "Turn client wins into compelling case studies",
          "Own SEO-aware content that ranks and reads well simultaneously",
          "Maintain a consistent content calendar and editorial quality across channels",
        ],
        requirements: [
          "Strong written English with a real portfolio or writing samples",
          "Ability to translate technical work into simple, compelling language",
          "Basic SEO awareness — you don't need to be an expert, just not ignore it",
          "Comfortable interviewing team members or clients for case study material",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience writing for a software, SaaS, or tech company",
          "Familiarity with SEO tools like Google Search Console",
          "Comfortable with basic email marketing platforms",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "growth-marketing-executive",
        title: "Growth Marketing Executive",
        oneLiner: "Run the experiments that find what actually moves the needle.",
        summary:
          "You'll design and run growth experiments across landing pages, funnels, and conversion paths — constantly testing what turns visitors into leads. This is a Performance-Based Opportunity built for someone who thinks in hypotheses and metrics, not gut feel.",
        responsibilities: [
          "Design and run growth experiments across acquisition and conversion",
          "Build and iterate on landing pages optimised for conversion",
          "Run conversion rate optimisation tests and document what wins",
          "Analyse funnels end-to-end to find where leads drop off",
          "Track and report on performance metrics with clear before/after impact",
        ],
        requirements: [
          "Analytical mindset with genuine comfort in data and experimentation",
          "Understanding of marketing funnels and conversion mechanics",
          "Comfortable with basic landing page or no-code tools",
          "Bias toward testing fast rather than debating in theory",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience with A/B testing or CRO tools",
          "Familiarity with Google Analytics or similar platforms",
          "Basic understanding of HTML/CSS for landing page tweaks",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
    ],
  },

  {
    id: "technical",
    code: "T",
    name: "Technical",
    tagline: "Build the AI products, SaaS, and software that ship.",
    description:
      "The technical team at 221B Labs builds real, shipped products — AI solutions, SaaS platforms, websites, mobile apps, automation systems, and internal tools — for businesses that need them to actually work. We care about end-to-end ownership: you don't just write code, you own the outcome from idea to production. If you'd rather build something real than sit through another sprint ceremony, this is the team.",
    roles: [
      {
        id: "full-stack-developer",
        title: "Full Stack Developer",
        oneLiner: "Own a feature from database to screen, no hand-offs required.",
        summary:
          "You'll build across the entire stack — schema, API, and the interface a user actually touches — for our client products and internal tools. This is a Performance-Based Opportunity for a developer who wants real end-to-end ownership rather than a narrow slice of a much bigger project.",
        responsibilities: [
          "Build features end-to-end: database schema, backend logic, and frontend UI",
          "Own deployment of your own work rather than throwing it over a wall",
          "Work directly with clients or internal stakeholders to scope features",
          "Balance moving fast with not accumulating unnecessary technical debt",
          "Support and extend existing products across multiple concurrent projects",
        ],
        requirements: [
          "Demonstrated experience across frontend and backend development",
          "Can take a feature from a rough spec to a shipped, working state independently",
          "Comfortable in ambiguous, fast-moving, early-stage environments",
          "Solid understanding of APIs, databases, and modern web frameworks",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience with React and Node.js/Django specifically",
          "Exposure to cloud deployment or basic DevOps",
          "Experience working directly with external clients",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "ai-ml-engineer",
        title: "AI / ML Engineer",
        oneLiner: "Build the intelligence behind our AI products.",
        summary:
          "You'll build and integrate the AI capabilities that power our products — LLM integrations, computer vision, NLP, and intelligent automation for real client use cases. This is a Performance-Based Opportunity for someone who wants to build applied AI systems that ship, not just experiment in a notebook.",
        responsibilities: [
          "Integrate LLMs and AI APIs into client and internal products",
          "Build and fine-tune AI models for specific business use cases",
          "Work on computer vision and NLP applications where relevant",
          "Design intelligent automation systems that reduce manual work for clients",
          "Own the reliability and performance of deployed AI features",
        ],
        requirements: [
          "Working knowledge of machine learning fundamentals and at least one ML framework",
          "Experience integrating or working with LLMs and AI APIs",
          "Comfortable reading research and translating it into production code",
          "Strong Python skills",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience with computer vision or NLP-specific libraries",
          "Exposure to prompt engineering or RAG-based systems",
          "Familiarity with model deployment and monitoring",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "mobile-app-developer",
        title: "Mobile App Developer",
        oneLiner: "Ship apps people actually keep on their home screen.",
        summary:
          "You'll build native and cross-platform mobile apps for our clients — from Android and iOS specifics to Flutter or React Native builds that need to feel fast and native. This is a Performance-Based Opportunity for a developer who wants real ownership over apps that go live in production, not side projects that never ship.",
        responsibilities: [
          "Build and maintain mobile applications on Android and/or iOS",
          "Develop cross-platform apps using Flutter or React Native where appropriate",
          "Integrate mobile apps with backend APIs and third-party services",
          "Own app store deployment, updates, and release cycles",
          "Debug and resolve performance or platform-specific issues",
        ],
        requirements: [
          "Working experience building and shipping mobile applications",
          "Familiarity with Flutter, React Native, or native Android/iOS development",
          "Understanding of REST API integration on mobile",
          "Comfortable with app store submission and release processes",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience shipping apps live on the Play Store or App Store",
          "Familiarity with push notifications, deep linking, or offline-first design",
          "Basic backend knowledge for full-cycle debugging",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "devops-cloud-engineer",
        title: "DevOps & Cloud Engineer",
        oneLiner: "Keep everything we ship running, fast, and secure.",
        summary:
          "You'll own the infrastructure, CI/CD pipelines, and cloud environments that keep our products running reliably in production. This is a Performance-Based Opportunity for someone who wants real ownership over uptime, deployment speed, and security — not just tickets in a queue.",
        responsibilities: [
          "Build and maintain CI/CD pipelines for faster, safer deployments",
          "Manage containerised environments using Docker",
          "Own cloud infrastructure setup, scaling, and cost efficiency",
          "Set up monitoring and alerting to catch issues before clients do",
          "Implement security best practices across our infrastructure",
        ],
        requirements: [
          "Working knowledge of CI/CD tools and Docker",
          "Experience with at least one major cloud provider (AWS, GCP, or Azure)",
          "Understanding of monitoring, logging, and incident response basics",
          "Security-conscious approach to infrastructure decisions",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience with Kubernetes or container orchestration",
          "Familiarity with infrastructure-as-code tools like Terraform",
          "Exposure to cloud cost optimisation",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
    ],
  },

  {
    id: "design",
    code: "D",
    name: "Design",
    tagline: "Design that looks, feels, and works like it was made on purpose.",
    description:
      "Design at 221B Labs shapes how our products and our brand feel — from client-facing interfaces to the visual language that represents us everywhere. We work in tight loops with developers and marketers, so your work doesn't sit in a file, it ships. If you care about the details other people don't notice until they're missing, we want you on this team.",
    roles: [
      {
        id: "ui-ux-designer",
        title: "UI/UX Designer",
        oneLiner: "Design interfaces that make sense the first time, every time.",
        summary:
          "You'll design wireframes, prototypes, and final interfaces for our client and internal products, working closely with developers to make sure what you design is what actually ships. This is a Performance-Based Opportunity for a designer who wants real product impact, not just polished mockups nobody builds.",
        responsibilities: [
          "Design wireframes and user flows based on real user research",
          "Build high-fidelity prototypes in Figma for client and internal products",
          "Maintain and extend a consistent design system across projects",
          "Collaborate closely with developers on feasible, buildable designs",
          "Review shipped UI against original designs and flag inconsistencies",
        ],
        requirements: [
          "Strong Figma skills and a portfolio showing real UI/UX work",
          "Understanding of usability principles, not just visual polish",
          "Comfortable conducting or applying basic user research",
          "Ability to collaborate closely with engineering on trade-offs",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience designing for B2B/SaaS or dashboard-heavy products",
          "Basic understanding of frontend constraints",
          "Familiarity with design systems at scale",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "graphic-designer",
        title: "Graphic Designer",
        oneLiner: "Make every asset we put out look like it belongs to a real brand.",
        summary:
          "You'll design the social, marketing, and presentation assets that represent 221B Labs everywhere — turning rough briefs into finished, on-brand visuals fast. This is a Performance-Based Opportunity for a designer who thrives on quick turnarounds without sacrificing quality.",
        responsibilities: [
          "Design social media graphics, decks, and marketing collateral",
          "Maintain visual consistency with brand guidelines across every asset",
          "Turn rough briefs from marketing or sales into finished visuals quickly",
          "Prepare print-ready files for physical collateral when needed",
          "Organise and maintain a shared, up-to-date asset library",
        ],
        requirements: [
          "Strong portfolio across social, digital, and print design",
          "Proficiency in tools like Figma, Photoshop, or Illustrator",
          "Fast turnaround without sacrificing quality — marketing moves quickly here",
          "Comfortable taking loosely defined briefs and running with them",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Basic motion graphics or animation skills",
          "Experience building assets for a consistent brand system",
          "Comfortable with quick social content turnaround cycles",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "editor",
        title: "Editor",
        oneLiner: "Make static things move — and make people stop scrolling.",
        summary:
          "You'll create Reels, promotional videos, and product demo content that gives 221B Labs a real, dynamic presence across social and marketing channels. This is a Performance-Based Opportunity for a video-first creator who understands what keeps someone watching past the first three seconds.",
        responsibilities: [
          "Edit Reels and short-form video for social and marketing campaigns",
          "Create promotional videos and product demo content",
          "Build basic motion graphics for explainer and campaign content",
          "Add captions, pacing, and sound design that keeps viewers watching",
          "Deliver assets in the right formats for each platform",
        ],
        requirements: [
          "Proficiency in a video editing tool (Premiere Pro, CapCut, or DaVinci Resolve)",
          "A portfolio or reel showing real edited work",
          "Understanding of short-form video pacing and platform-specific formats",
          "Comfortable working with rough footage or static assets and making them move",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Basic After Effects or motion graphics experience",
          "Experience shooting on a phone or basic camera setup",
          "Familiarity with product demo storytelling",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
      {
        id: "brand-designer",
        title: "Brand Designer",
        oneLiner: "Shape the visual language that makes 221B Labs recognisable anywhere.",
        summary:
          "You'll own our brand identity — logo systems, typography, and the visual language every other designer and marketer builds on. This is a Performance-Based Opportunity for someone who thinks about brand as a system, not a single logo file.",
        responsibilities: [
          "Develop and maintain brand identity systems, including logo usage",
          "Define typography, colour, and visual language guidelines",
          "Create and document design guidelines other teams can follow confidently",
          "Collaborate with marketing and product design to keep brand consistent everywhere",
          "Evolve the brand system as 221B Labs grows and takes on new markets",
        ],
        requirements: [
          "Strong portfolio demonstrating brand identity or systems-level design work",
          "Deep understanding of typography, colour theory, and visual language",
          "Ability to document guidelines clearly enough for non-designers to follow",
          "Comfortable balancing creative vision with practical brand consistency",
          "Open to freshers and experienced candidates alike",
        ],
        niceToHave: [
          "Experience building a brand system from early stage",
          "Familiarity with brand guideline documentation tools",
          "Exposure to packaging or print brand applications",
        ],
        employmentType: "Performance-Based Opportunity",
        location: "Remote / Hybrid (Depending on Project Requirements)",
        experience: "Open to Freshers & Experienced Candidates",
        compensation: {
          type: "Performance-Based",
          note: "Compensation, incentives, bonuses, and career growth are based on measurable performance, ownership, contribution, and business impact.",
        },
        benefits: [
          "Performance-based incentives",
          "Flexible work environment",
          "Mentorship from company leadership",
          "Opportunity to work on real client projects",
          "Rapid career growth",
          "Hands-on startup experience",
          "Certificate & Letter of Recommendation (Internships)",
          "Learning opportunities across multiple technologies",
        ],
      },
    ],
  },
];

/* Flat lookup helpers used by app.js */
function findDepartment(id){
  return DEPARTMENTS.find(d => d.id === id);
}
function findRole(deptId, roleId){
  const dept = findDepartment(deptId);
  if(!dept) return null;
  const role = dept.roles.find(r => r.id === roleId);
  return role ? { dept, role } : null;
}